version: "3.5"

volumes:
  grafana_data:
  go-carbon_data:

services:
  stats-getter:
    build:
      context: .
      dockerfile: ./src/pushStats/Dockerfile
    volumes:
      - ./logs/statsGetter:/app/logs
    depends_on:
      - carbon-relay-ng
    environment:
      - PREFIX=""
      - DISABLE_PUSHGATEWAY=false
      - SERVER_PORT=21025
      - INCLUDE_PUSH_STATUS_API=false
  carbon-relay-ng:
    image: grafana/carbon-relay-ng
    depends_on:
      - go-carbon
    volumes:
      - ./grafanaConfig/carbon-relay-ng:/conf
    expose:
      - 2003:2003
    healthcheck:
      test: nc -zv go-carbon:2003
      interval: 10s
      timeout: 1s
      retries: 3
  go-carbon:
    image: ghcr.io/go-graphite/go-carbon
    volumes:
      - ./grafanaConfig/go-carbon/go-carbon.conf:/etc/go-carbon/go-carbon.conf
      - ./grafanaConfig/go-carbon:/etc/go-carbon/
      - ./go-carbon-storage:/var/lib/graphite/whisper
      #- ./logs/goCarbon:/var/log/go-carbon
  carbon-api:
    image: pieterbrandsen/carbonapi-0.15.6
    volumes:
      - ./grafanaConfig/carbonapi/carbonapi.yml:/etc/carbonapi.yml
      - ./grafanaConfig/carbonapi:/conf:ro
      - ./logs/carbonApi:/log
    depends_on:
      - go-carbon
    healthcheck:
      test: "curl -fsSL -o /dev/null http://go-carbon:8080/lb_check"
      interval: 10s
      timeout: 1s
      retries: 3
  grafana:
    image: grafana/grafana-oss:9.3.6-ubuntu
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafanaConfig/grafana:/etc/grafana
      - ./logs/grafana:/var/log/grafana
    ports:
      - 3000:3000
    healthcheck:
      test: "curl -fsSL -o /dev/null http://grafana:3000"
      interval: 10s
      timeout: 1s
      retries: 3
  #t  labels:
  #t    - "traefik.enable=true"
  #t    - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
  #t    - "traefik.http.routers.grafana.entrypoints=web"
  #ttraefik:
  #t  image: traefik:latest
  #t  container_name: traefik
  #t  command:
  #t    - "--log.level=DEBUG"
  #t    - "--api.insecure=true"
  #t    - "--providers.docker=true"
  #t    - "--providers.docker.exposedbydefault=false"
  #t    - "--entrypoints.web.address=:80"
  #t  volumes:
  #t    - /var/run/docker.sock:/var/run/docker.sock
  #t  ports:
  #t    - 80:80
  #t    - 443:443