[http.middlewares.tado-redirect-org-regex.redirectregex]
  permanent = true
  regex = "^https?://tado\\.localhost(.*)"
  replacement = "http://grafana.localhost/?orgId=2"

[http.routers.tado-grafana]
  service = "grafana@docker"
  rule = "Host(`tado.localhost`)"
  middlewares = "tado-redirect-org-regex@file"